// Related to validation
export const ACTION_VALIDATION_FAILED = "VALIDATION_FAILED";

export const ACTION_GET_AUTH_KEY_SUCCEEDED = "GET_AUTH_KEY_SUCCEEDED";
// Related to Change type

export const ACTION_CHANGE_TYPE = "CHANGE_TYPE";
// Related to Login Check.
export const ACTION_CHECK_LOGIN_STARTED = "CHECK_LOGIN_STARTED";
export const ACTION_CHECK_LOGIN_EXIST = "CHECK_LOGIN_EXIST";
export const ACTION_CHECK_LOGIN_NOTEXIST = "CHECK_LOGIN_NOTEXIST";
export const ACTION_CHECK_LOGIN_FAILED = "CHECK_LOGIN_FAILED";

// Related to Login.
export const ACTION_LOGIN_STARTED = "LOGIN_STARTED";
export const ACTION_LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const ACTION_LOGIN_FAILED = "LOGIN_FAILED";
export const ACTION_GET_TEMP = "GET_TEMP";

// Related to Forget.
export const ACTION_FORGET_PASSWORD_STARTED = "FORGET_PASSWORD_STARTED";
export const ACTION_FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";
export const ACTION_FORGET_PASSWORD_FAILED = "FORGET_PASSWORD_FAILED";

// Related to send Forget.
export const ACTION_SEND_FORGET_PASSWORD_STARTED = "SEND_FORGET_PASSWORD_STARTED";
export const ACTION_SEND_FORGET_PASSWORD_SUCCESS = "SEND_FORGET_PASSWORD_SUCCESS";
export const ACTION_SEND_FORGET_PASSWORD_FAILED = "SEND_FORGET_PASSWORD_FAILED";

export const ACTION_CREATE_NEW_PASSWORD_STARTED = "CREATE_NEW_PASSWORD_STARTED";
export const ACTION_CREATE_NEW_PASSWORD_SUCCESS = "CREATE_NEW_PASSWORD_SUCCESS";
export const ACTION_CREATE_NEW_PASSWORD_FAILED = "CREATE_NEW_PASSWORD_FAILED";

// Related to log out method
export const ACTION_LOGOUT_STARTED = "LOG_OUT_STARTED"
export const ACTION_LOGOUT_FAILED = "LOG_OUT_FAILED"
export const ACTION_LOGGED_OUT = "LOGGED_OUT";

// Related to registration
export const ACTION_REGISTRATION_STARTED = "REGISTRATION_STARTED";
export const ACTION_REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const ACTION_REGISTRATION_FAILED = "REGISTRATION_FAILED";
export const ACTION_CLEAR_REGISTRATION = "REGISTRATION_CLEARED";

export const ACTION_GET_REGIONS_STARTED = "GET_REGIONS_STARTED";
export const ACTION_GET_REGIONS_SUCCEEDED = "GET_REGIONS_SUCCEEDED";
export const ACTION_GET_REGIONS_FAILED = "GET_REGIONS_FAILED";

export const ACTION_GET_PROFILE_STARTED = "GET_PROFILE_STARTED";
export const ACTION_GET_PROFILE_SUCCEEDED = "GET_PROFILE_SUCCEEDED";
export const ACTION_GET_PROFILE_FAILED = "GET_PROFILE_FAILED";

export const ACTION_GET_ROLES_STARTED = "GET_ROLES_STARTED";
export const ACTION_GET_ROLES_SUCCEEDED = "GET_ROLES_SUCCEEDED";
export const ACTION_GET_ROLES_FAILED = "GET_ROLES_FAILED";

export const ACTION_UPDATE_PROFILE_STARTED = "UPDATE_PROFILE_STARTED";
export const ACTION_UPDATE_PROFILE_SUCCEEDED = "UPDATE_PROFILE_SUCCEEDED";
export const ACTION_UPDATE_PROFILE_FAILED = "UPDATE_PROFILE_FAILED";

export const ACTION_ADD_BLACK_LIST_STARTED = "ADD_BLACK_LIST_STARTED";
export const ACTION_ADD_BLACK_LIST_SUCCEEDED = "ADD_BLACK_LIST_SUCCEEDED";
export const ACTION_ADD_BLACK_LIST_FAILED = "ADD_BLACK_LIST_FAILED";

export const ACTION_UPDATE_AVATAR_STARTED = "UPDATE_AVATAR_STARTED";
export const ACTION_UPDATE_AVATAR_SUCCEEDED = "UPDATE_AVATAR_SUCCEEDED";
export const ACTION_UPDATE_AVATAR_FAILED = "UPDATE_AVATAR_FAILED";

export const ACTION_DELETE_AVATAR_STARTED = "DELETE_AVATAR_STARTED";
export const ACTION_DELETE_AVATAR_SUCCEEDED = "DELETE_AVATAR_SUCCEEDED";
export const ACTION_DELETE_AVATAR_FAILED = "DELETE_AVATAR_FAILED";

// related to offers
export const ACTION_GET_OFFERS_STARTED = "GET_OFFERS_STARTED";
export const ACTION_GET_OFFERS_SUCCEEDED = "GET_OFFERS_SUCCEEDED";
export const ACTION_GET_OFFERS_FAILED = "GET_OFFERS_FAILED";

export const ACTION_GET_OFFER_COMPANY_STARTED = "GET_OFFER_COMPANY_STARTED";
export const ACTION_GET_OFFER_COMPANY_SUCCEEDED = "GET_OFFER_COMPANY_SUCCEEDED";
export const ACTION_GET_OFFER_COMPANY_FAILED = "GET_OFFER_COMPANY_FAILED";

export const ACTION_ADD_OFFER_STARTED = "ADD_OFFER_STARTED";
export const ACTION_ADD_OFFER_SUCCEEDED = "ADD_OFFER_SUCCEEDED";
export const ACTION_ADD_OFFER_FAILED = "ADD_OFFER_FAILED";

export const ACTION_DELETE_OFFER_STARTED = "DELETE_OFFER_STARTED";
export const ACTION_DELETE_OFFER_SUCCEEDED = "DELETE_OFFER_SUCCEEDED";
export const ACTION_DELETE_OFFER_FAILED = "DELETE_OFFER_FAILED";

export const ACTION_EDIT_OFFER_STARTED = "EDIT_OFFER_STARTED";
export const ACTION_EDIT_OFFER_SUCCEEDED = "EDIT_OFFER_SUCCEEDED";
export const ACTION_EDIT_OFFER_FAILED = "EDIT_OFFER_FAILED";
// related to demands
export const ACTION_GET_DEMANDS_STARTED = "GET_DEMANDS_STARTED";
export const ACTION_GET_DEMANDS_SUCCEEDED = "GET_DEMANDS_SUCCEEDED";
export const ACTION_GET_DEMANDS_FAILED = "GET_DEMANDS_FAILED";

export const ACTION_GET_DEMAND_COMPANY_STARTED = "GET_DEMAND_COMPANY_STARTED";
export const ACTION_GET_DEMAND_COMPANY_SUCCEEDED = "GET_DEMAND_COMPANY_SUCCEEDED";
export const ACTION_GET_DEMAND_COMPANY_FAILED = "GET_DEMAND_COMPANY_FAILED";

export const ACTION_ADD_DEMAND_STARTED = "ADD_DEMAND_STARTED";
export const ACTION_ADD_DEMAND_SUCCEEDED = "ADD_DEMAND_SUCCEEDED";
export const ACTION_ADD_DEMAND_FAILED = "ADD_DEMAND_FAILED";

export const ACTION_DELETE_DEMAND_STARTED = "DELETE_DEMAND_STARTED";
export const ACTION_DELETE_DEMAND_SUCCEEDED = "DELETE_DEMAND_SUCCEEDED";
export const ACTION_DELETE_DEMAND_FAILED = "DELETE_DEMAND_FAILED";

export const ACTION_EDIT_DEMAND_STARTED = "EDIT_DEMAND_STARTED";
export const ACTION_EDIT_DEMAND_SUCCEEDED = "EDIT_DEMAND_SUCCEEDED";
export const ACTION_EDIT_DEMAND_FAILED = "EDIT_DEMAND_FAILED";

export const ACTION_ADD_DEMAND_STOREHOUSE_CARD_STARTED = "ADD_DEMAND_STOREHOUSE_CARD_STARTED";
export const ACTION_ADD_DEMAND_STOREHOUSE_CARD_SUCCEEDED = "ADD_DEMAND_STOREHOUSE_CARD_SUCCEEDED";
export const ACTION_ADD_DEMAND_STOREHOUSE_CARD_FAILED = "ADD_DEMAND_STOREHOUSE_CARD_FAILED";

export const ACTION_GET_DEMAND_STOREHOUSE_CARD_STARTED = "GET_DEMAND_STOREHOUSE_CARD_STARTED";
export const ACTION_GET_DEMAND_STOREHOUSE_CARD_SUCCEEDED = "GET_DEMAND_STOREHOUSE_CARD_SUCCEEDED";
export const ACTION_GET_DEMAND_STOREHOUSE_CARD_FAILED = "GET_DEMAND_STOREHOUSE_CARD_FAILED";

// related to news
export const ACTION_GET_NEWS_STARTED = "GET_NEWS_STARTED";
export const ACTION_GET_NEWS_SUCCEEDED = "GET_NEWS_SUCCEEDED";
export const ACTION_GET_NEWS_FAILED = "GET_NEWS_FAILED";

export const ACTION_GET_NEWS_BY_DATE_STARTED = "GET_NEWS_BY_DATE_STARTED";
export const ACTION_GET_NEWS_BY_DATE_SUCCEEDED = "GET_NEWS_BY_DATE_SUCCEEDED";
export const ACTION_GET_NEWS_BY_DATE_FAILED = "GET_NEWS_BY_DATE_FAILED";


// related to feedback
export const ACTION_SEND_FEEDBACK_STARTED = "SEND_FEEDBACK_STARTED";
export const ACTION_SEND_FEEDBACK_SUCCEEDED = "SEND_FEEDBACK_SUCCEEDED";
export const ACTION_SEND_FEEDBACK_FAILED = "SEND_FEEDBACK_FAILED";

// related to companies
export const ACTION_GET_COMPANIES_STARTED = "GET_COMPANIES_STARTED";
export const ACTION_GET_COMPANIES_SUCCEEDED = "GET_COMPANIES_SUCCEEDED";
export const ACTION_GET_COMPANIES_FAILED = "GET_COMPANIES_FAILED";

export const ACTION_GET_ALL_COMPANIES_STARTED = "GET_ALL_COMPANIES_STARTED";
export const ACTION_GET_ALL_COMPANIES_SUCCEEDED = "GET_ALL_COMPANIES_SUCCEEDED";
export const ACTION_GET_ALL_COMPANIES_FAILED = "GET_ALL_COMPANIES_FAILED";

export const ACTION_GET_COMPANY_TYPES_STARTED = "GET_COMPANY_TYPES_STARTED";
export const ACTION_GET_COMPANY_TYPES_SUCCEEDED = "GET_COMPANY_TYPES_SUCCEEDED";
export const ACTION_GET_COMPANY_TYPES_FAILED = "GET_COMPANY_TYPES_FAILED";

export const ACTION_GET_DOCUMENT_TYPES_STARTED = "GET_DOCUMENT_TYPES_STARTED";
export const ACTION_GET_DOCUMENT_TYPES_SUCCEEDED = "GET_DOCUMENT_TYPES_SUCCEEDED";
export const ACTION_GET_DOCUMENT_TYPES_FAILED = "GET_DOCUMENT_TYPES_FAILED";

export const ACTION_GET_COMPANY_SEGMENT_STARTED = "GET_COMPANY_SEGMENT_STARTED";
export const ACTION_GET_COMPANY_SEGMENT_SUCCEEDED = "GET_COMPANY_SEGMENT_SUCCEEDED";
export const ACTION_GET_COMPANY_SEGMENT_FAILED = "GET_COMPANY_SEGMENT_FAILED";

export const ACTION_GET_TRADESMAN_LIST_STARTED = "GET_TRADESMAN_LIST_STARTED";
export const ACTION_GET_TRADESMAN_LIST_SUCCEEDED = "GET_TRADESMAN_LIST_SUCCEEDED";
export const ACTION_GET_TRADESMAN_LIST_FAILED = "GET_TRADESMAN_LIST_FAILED";

export const ACTION_GET_STATION_LIST_STARTED = "GET_STATION_LIST_STARTED";
export const ACTION_GET_STATION_LIST_SUCCEEDED = "GET_STATION_LIST_SUCCEEDED";
export const ACTION_GET_STATION_LIST_FAILED = "GET_STATION_LIST_FAILED";

export const ACTION_GET_BANK_INFO_STARTED = "GET_BANK_INFO_STARTED";
export const ACTION_GET_BANK_INFO_SUCCEEDED = "GET_BANK_INFO_SUCCEEDED";
export const ACTION_GET_BANK_INFO_FAILED = "GET_BANK_INFO_FAILED";

export const ACTION_GET_STANDART_LIST_STARTED = "GET_STANDART_LIST_STARTED";
export const ACTION_GET_STANDART_LIST_SUCCEEDED = "GET_STANDART_LIST_SUCCEEDED";
export const ACTION_GET_STANDART_LIST_FAILED = "GET_STANDART_LIST_FAILED";

export const ACTION_GET_DELIVERY_CONS_STARTED = "GET_DELIVERY_CONS_STARTED";
export const ACTION_GET_DELIVERY_CONS_SUCCEEDED = "GET_DELIVERY_CONS_SUCCEEDED";
export const ACTION_GET_DELIVERY_CONS_FAILED = "GET_DELIVERY_CONS_FAILED";

// related to store
export const ACTION_GET_STOREHOUSE_LIST_STARTED = "GET_STOREHOUSE_LIST_STARTED";
export const ACTION_GET_STOREHOUSE_LIST_SUCCEEDED = "GET_STOREHOUSE_LIST_SUCCEEDED";
export const ACTION_GET_STOREHOUSE_LIST_FAILED = "GET_STOREHOUSE_LIST_FAILED";

export const ACTION_GET_STOREKEEPER_STARTED = "GET_STOREKEEPER_STARTED";
export const ACTION_GET_STOREKEEPER_SUCCEEDED = "GET_STOREKEEPER_SUCCEEDED";
export const ACTION_GET_STOREKEEPER_FAILED = "GET_STOREKEEPER_FAILED";

export const ACTION_ADD_TARIFF_STARTED = "ADD_TARIFF_STARTED";
export const ACTION_ADD_TARIFF_SUCCEEDED = "ADD_TARIFF_SUCCEEDED";
export const ACTION_ADD_TARIFF_FAILED = "ADD_TARIFF_FAILED";

export const ACTION_GET_TARIFF_STARTED = "GET_TARIFF_STARTED";
export const ACTION_GET_TARIFF_SUCCEEDED = "GET_TARIFF_SUCCEEDED";
export const ACTION_GET_TARIFF_FAILED = "GET_TARIFF_FAILED";

export const ACTION_EDIT_TARIFF_STARTED = "EDIT_TARIFF_STARTED";
export const ACTION_EDIT_TARIFF_SUCCEEDED = "EDIT_TARIFF_SUCCEEDED";
export const ACTION_EDIT_TARIFF_FAILED = "EDIT_TARIFF_FAILED";

export const ACTION_DELETE_TARIFF_STARTED = "DELETE_TARIFF_STARTED";
export const ACTION_DELETE_TARIFF_SUCCEEDED = "DELETE_TARIFF_SUCCEEDED";
export const ACTION_DELETE_TARIFF_FAILED = "DELETE_TARIFF_FAILED";

// related to resources
export const ACTION_GET_CATEGORIES_STARTED = "GET_CATEGORIES_STARTED";
export const ACTION_GET_CATEGORIES_SUCCEEDED = "GET_CATEGORIES_SUCCEEDED";
export const ACTION_GET_CATEGORIES_FAILED = "GET_CATEGORIES_FAILED";

export const ACTION_GET_RESOURCES_STARTED = "GET_RESOURCES_STARTED";
export const ACTION_GET_RESOURCES_SUCCEEDED = "GET_RESOURCES_SUCCEEDED";
export const ACTION_GET_RESOURCES_FAILED = "GET_RESOURCES_FAILED";

export const ACTION_GET_MEASURE_LIST_STARTED = "GET_MEASURE_LIST_STARTED";
export const ACTION_GET_MEASURE_LIST_SUCCEEDED = "GET_MEASURE_LIST_SUCCEEDED";
export const ACTION_GET_MEASURE_LIST_FAILED = "GET_MEASURE_LIST_FAILED";

export const ACTION_GET_EXPEDITOR_LIST_STARTED = "GET_EXPEDITOR_LIST_STARTED";
export const ACTION_GET_EXPEDITOR_LIST_SUCCEEDED = "GET_EXPEDITOR_LIST_SUCCEEDED";
export const ACTION_GET_EXPEDITOR_LIST_FAILED = "GET_EXPEDITOR_LIST_FAILED";

export const ACTION_GET_PRODUCERS_STARTED = "GET_PRODUCERS_STARTED";
export const ACTION_GET_PRODUCERS_SUCCEEDED = "GET_PRODUCERS_SUCCEEDED";
export const ACTION_GET_PRODUCERS_FAILED = "GET_PRODUCERS_FAILED";

// related to contracts
export const ACTION_CREATE_CONTRACT_STARTED = "CREATE_CONTRACT_STARTED";
export const ACTION_CREATE_CONTRACT_SUCCEEDED = "CREATE_CONTRACT_SUCCEEDED";
export const ACTION_CREATE_CONTRACT_FAILED = "CREATE_CONTRACT_FAILED";

export const ACTION_GET_CONTRACT_STARTED = "GET_CONTRACT_STARTED";
export const ACTION_GET_CONTRACT_SUCCEEDED = "GET_CONTRACT_SUCCEEDED";
export const ACTION_GET_CONTRACT_FAILED = "GET_CONTRACT_FAILED";

export const ACTION_GET_CONTRACT_LIST_STARTED = "GET_CONTRACT_LIST_STARTED";
export const ACTION_GET_CONTRACT_LIST_SUCCEEDED = "GET_CONTRACT_LIST_SUCCEEDED";
export const ACTION_GET_CONTRACT_LIST_FAILED = "GET_CONTRACT_LIST_FAILED";

export const ACTION_GET_CONTRACT_LIST_FILTER_STARTED = "GET_CONTRACT_LIST_FILTER_STARTED";
export const ACTION_GET_CONTRACT_LIST_FILTER_SUCCEEDED = "GET_CONTRACT_LIST_FILTER_SUCCEEDED";
export const ACTION_GET_CONTRACT_LIST_FILTER_FAILED = "GET_CONTRACT_LIST_FILTER_FAILED";

export const ACTION_GET_CONTRACT_LIST_FILTER_TIME_STARTED = "GET_CONTRACT_LIST_FILTER_TIME_STARTED";
export const ACTION_GET_CONTRACT_LIST_FILTER_TIME_SUCCEEDED = "GET_CONTRACT_LIST_FILTER_TIME_SUCCEEDED";
export const ACTION_GET_CONTRACT_LIST_FILTER_TIME_FAILED = "GET_CONTRACT_LIST_FILTER_TIME_FAILED";

export const ACTION_APPROVE_CONTRACT_STARTED = "APPROVE_CONTRACT_STARTED";
export const ACTION_APPROVE_CONTRACT_SUCCEEDED = "APPROVE_CONTRACT_SUCCEEDED";
export const ACTION_APPROVE_CONTRACT_FAILED = "APPROVE_CONTRACT_FAILED";

export const ACTION_SIGN_CONTRACT_STARTED = "SIGN_CONTRACT_STARTED";
export const ACTION_SIGN_CONTRACT_SUCCEEDED = "SIGN_CONTRACT_SUCCEEDED";
export const ACTION_SIGN_CONTRACT_FAILED = "SIGN_CONTRACT_FAILED";

export const ACTION_SENDING_DOC_STARTED = "SENDING_DOC_STARTED";
export const ACTION_SENDING_DOC_SUCCEEDED = "SENDING_DOC_SUCCEEDED";
export const ACTION_SENDING_DOC_FAILED = "SENDING_DOC_FAILED";

export const ACTION_SAVE_DOC_INFO_STARTED = "SAVE_DOC_INFO_STARTED";
export const ACTION_SAVE_DOC_INFO_SUCCEEDED = "SAVE_DOC_INFO_SUCCEEDED";
export const ACTION_SAVE_DOC_INFO_FAILED = "SAVE_DOC_INFO_FAILED";

// related to chat
export const ACTION_GET_MY_CHATS_STARTED = "GET_MY_CHATS_STARTED";
export const ACTION_GET_MY_CHATS_SUCCEEDED = "GET_MY_CHATS_SUCCEEDED";
export const ACTION_GET_MY_CHATS_FAILED = "GET_MY_CHATS_FAILED";

export const ACTION_GET_COUNT_CHATS_STARTED = "GET_COUNT_CHATS_STARTED";
export const ACTION_GET_COUNT_CHATS_SUCCEEDED = "GET_COUNT_CHATS_SUCCEEDED";
export const ACTION_GET_COUNT_CHATS_FAILED = "GET_COUNT_CHATS_FAILED";

export const ACTION_GET_CHAT_STARTED = "GET_CHAT_STARTED";
export const ACTION_GET_CHAT_SUCCEEDED = "GET_CHAT_SUCCEEDED";
export const ACTION_GET_CHAT_FAILED = "GET_CHAT_FAILED";

export const ACTION_SEND_MESSAGE_STARTED = "SEND_MESSAGE_STARTED";
export const ACTION_SEND_MESSAGE_SUCCEEDED = "SEND_MESSAGE_SUCCEEDED";
export const ACTION_SEND_MESSAGE_FAILED = "SEND_MESSAGE_FAILED";

export const ACTION_READ_MESSAGE_STARTED = "READ_MESSAGE_STARTED";
export const ACTION_READ_MESSAGE_SUCCEEDED = "READ_MESSAGE_SUCCEEDED";
export const ACTION_READ_MESSAGE_FAILED = "READ_MESSAGE_FAILED";

// get expeditor tarif
export const ACTION_GET_EXPEDITOR_STARTED = "GET_EXPEDITOR_STARTED";
export const ACTION_GET_EXPEDITOR_SUCCEEDED = "GET_EXPEDITOR_SUCCEEDED";
export const ACTION_GET_EXPEDITOR_FAILED = "GET_EXPEDITOR_FAILED";

export const ACTION_ADD_EXPEDITOR_TARIFF_STARTED = "ADD_EXPEDITOR_TARIFF_STARTED";
export const ACTION_ADD_EXPEDITOR_TARIFF_SUCCEEDED = "ADD_EXPEDITOR_TARIFF_SUCCEEDED";
export const ACTION_ADD_EXPEDITOR_TARIFF_FAILED = "ADD_EXPEDITOR_TARIFF_FAILED";

// Related to Trade.
export const ACTION_GET_AUTH_KEY_STARTED = "GET_AUTH_KEY_STARTED";
export const ACTION_GET_AUTH_KEY_SUCCESS = "GET_AUTH_KEY_SUCCESS";
export const ACTION_GET_AUTH_KEY_FAILED = "GET_AUTH_KEY_FAILED";

export const ACTION_SEND_SIGN_STARTED = "SEND_SIGN_STARTED";
export const ACTION_SEND_SIGN_SUCCESS = "SEND_SIGN_SUCCESS";
export const ACTION_SEND_SIGN_FAILED = "SEND_SIGN_FAILED";


// Related to Review
export const ACTION_SEND_PREVIEW_STARTED = "SEND_PREVIEW_STARTED";
export const ACTION_SEND_PREVIEW_SUCCESS = "SEND_PREVIEW_SUCCESS";
export const ACTION_SEND_PREVIEW_FAILED = "SEND_PREVIEW_FAILED";

export const ACTION_GET_PREVIEW_STARTED = "GET_PREVIEW_STARTED";
export const ACTION_GET_PREVIEW_SUCCEEDED = "GET_PREVIEW_SUCCEEDED";
export const ACTION_GET_PREVIEW_FAILED = "GET_PREVIEW_FAILED";

// Related to send gallery.
export const ACTION_SEND_GALLERY_STARTED = "SEND_GALLERY_STARTED";
export const ACTION_SEND_GALLERY_SUCCESS = "SEND_GALLERY_SUCCESS";
export const ACTION_SEND_GALLERY_FAILED = "SEND_GALLERY_FAILED";

export const ACTION_GET_GALLERY_STARTED = "GET_GALLERY_STARTED";
export const ACTION_GET_GALLERY_SUCCESS = "GET_GALLERY_SUCCESS";
export const ACTION_GET_GALLERY_FAILED = "GET_GALLERY_FAILED";

// get graph

export const ACTION_GET_GRAPH_STARTED = "GET_GRAPH_STARTED";
export const ACTION_GET_GRAPH_SUCCEEDED = "GET_GRAPH_SUCCEEDED";
export const ACTION_GET_GRAPH_FAILED = "GET_GRAPH_FAILED";

export const ACTION_GET_GRAPH_SEGMENTATION_STARTED = "GET_GRAPH_SEGMENTATION_STARTED";
export const ACTION_GET_GRAPH_SEGMENTATION_SUCCEEDED = "GET_GRAPH_SEGMENTATION_SUCCEEDED";
export const ACTION_GET_GRAPH_SEGMENTATION_FAILED = "GET_GRAPH_SEGMENTATION_FAILED";

export const ACTION_GET_GRAPH_DATE_STARTED = "GET_GRAPH_DATE_STARTED";
export const ACTION_GET_GRAPH_DATE_SUCCEEDED = "GET_GRAPH_DATE_SUCCEEDED";
export const ACTION_GET_GRAPH_DATE_FAILED = "GET_GRAPH_DATE_FAILED";

// payments

export const ACTION_GET_PAYBOX_URL_STARTED = "GET_PAYBOX_URL_STARTED";
export const ACTION_GET_PAYBOX_URL_SUCCEEDED = "GET_PAYBOX_URL_SUCCEEDED";
export const ACTION_GET_PAYBOX_URL_FAILED = "GET_PAYBOX_URL_FAILED";

export const ACTION_GET_PAYMENT_RECEIPT_STARTED = "GET_PAYMENT_RECEIPT_STARTED";
export const ACTION_GET_PAYMENT_RECEIPT_SUCCEEDED = "GET_PAYMENT_RECEIPT_SUCCEEDED";
export const ACTION_GET_PAYMENT_RECEIPT_FAILED = "GET_PAYMENT_RECEIPT_FAILED";